/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("mn.tqt.kotlin-application-conventions")
}
application {
    // Define the main class for the application.
    mainClass.set("mn.tqt.local_kafka_initializer.KafkaInitializerKT")
}

dependencies {
    implementation(libs.jackson)
    implementation(libs.kafkaclients)
}