/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "tqt"
include("app", "localKafkaInitializer")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            library("kafkaclients", "org.apache.kafka:kafka-clients:3.6.1")
            library("jackson", "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.16.0")
        }
    }
}