GET http://localhost:8080/generate-dummy-data
Accept: application/json

###
POST http://localhost:8080
Content-Type: application/json

{
  "startDate": "2023-12-16",
  "endDate": "2023-12-18",
  "kafkaEndpoint": "localhost:9094",
  "kafkaTopic": "my-topic",
  "schemaRegistry": "localhost:9091",
  "schema": {
    "type": "EXCLUDE",
    "schema": [
      "a.b.c",
      "a.d"
    ]
  }
}

###
