/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("mn.tqt.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

application {
    // Define the main class for the application.
    mainClass.set("mn.tqt.app.AppKt")
}
