/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package mn.tqt.local_kafka_initializer

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class AppKtTest {
    @Test fun testConstructor() {
        val list = AppKt()
        assertEquals(0, list.size())
    }

    @Test fun testAdd() {
        val list = AppKt()

        list.add("one")
        assertEquals(1, list.size())
        assertEquals("one", list.get(0))

        list.add("two")
        assertEquals(2, list.size())
        assertEquals("two", list.get(1))
    }

    @Test fun testRemove() {
        val list = AppKt()

        list.add("one")
        list.add("two")
        assertTrue(list.remove("one"))

        assertEquals(1, list.size())
        assertEquals("two", list.get(0))

        assertTrue(list.remove("two"))
        assertEquals(0, list.size())
    }

    @Test fun testRemoveMissing() {
        val list = AppKt()

        list.add("one")
        list.add("two")
        assertFalse(list.remove("three"))
        assertEquals(2, list.size())
    }
}
