/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mn.tqt.local_kafka_initializer

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import java.io.Serializable

fun main() {
    val dummyJson = object : Serializable {
        val property1 = "aaa"
        val property2 = 2
    }

    val objectmapper = ObjectMapper()

    val parsedJson = objectmapper.valueToTree<JsonNode>(dummyJson)
    println(parsedJson)
}